### ISSUE TITLE
Drupal core decision

### ISSUE THREAD

**Issue by asghaier** [gnulugtn/portal#3]
Evaluate the followin:
- [x] Drupal 8 features discovery https://github.com/gnulugtn/portal/issues/5
- [x]  Drupal 8 theming discovery https://github.com/gnulugtn/portal/issues/6
- [x]  Drupal 8 modules discovery https://github.com/gnulugtn/portal/issues/7

**Comment by asghaier** [comment]
Drupal 8 offers great and better features out of the box. But contributed modules are far less than Drupal 7 what makes developing a full featured community portal with Drupal 8 extremely hard in the next 12 months.
Decision is to go with Drupal 7 even though its core features and capabilities are lagging behind Drupal 8 (tough some Drupal 8 core features has been backported to Drupal 7 as contributed modules)
